# application.properties in central node
server.port=8080

# Logging level
logging.level.org.springframework=INFO

# Backend module URLs
account.module.urlPrefix=http://localhost:8081
wellnesszone.module.urlPrefix=http://localhost:8085